[package]
name = "blockchain"
version = "0.1.0"
edition = "2018"
description = "A proof of work Blockchain"
repository = "https://github.com/tsauvajon/blockchain"
readme = "README.md"
license = "MIT"
keywords = ["blobkchain"]
categories = ["blockchain"]

[dependencies]
blake3 = "0.3.7"
